function_calls:
  - rule: TimeUsage
    package: time
    functions: [Now, Since, Sleep]
    severity: error
    message: "Detected time.%FUNC%() in workflow. Use workflow.Now(ctx)/workflow.Sleep(ctx) instead."

  - rule: Randomness
    package: math/rand
    functions: [Intn, Int, Float32, Float64, Read]
    severity: error
    message: "Detected rand.%FUNC%() in workflow. Avoid nondeterminism; use workflow.SideEffect if needed."

  - rule: IOCalls
    package: os
    functions: [Open, OpenFile, ReadFile, WriteFile, Mkdir, Remove]
    severity: error
    message: "Detected os.%FUNC%() in workflow. Avoid file I/O inside workflows."

  - rule: IOCalls
    package: fmt
    functions: [Println, Printf, Print]
    severity: warning
    message: "Detected fmt.%FUNC%() in workflow. Use workflow.GetLogger(ctx) instead."

  - rule: Network
    package: net/http
    functions: [Get, Post, Do, Head]
    severity: error
    message: "Detected HTTP call in workflow. Use workflow activities for network calls."

disallowed_imports:
  - rule: ImportRandom
    path: math/rand
    severity: warning
    message: "Importing math/rand in files with workflows is discouraged; consider deterministic alternatives."

# External package rules for common third-party libraries
external_packages:
  # UUID Generation (very common issue)
  - rule: UUIDGeneration
    package: github.com/google/uuid
    functions: [New, NewRandom, NewString]
    severity: error
    message: "UUID generation is non-deterministic. Use workflow.SideEffect for UUID generation in workflows."

  # Popular HTTP client libraries
  - rule: HTTPClient
    package: github.com/go-resty/resty/v2
    functions: [Get, Post, Put, Delete, Execute]
    severity: error
    message: "HTTP calls should be performed in activities, not directly in workflows."

  # Redis operations (common in microservices)
  - rule: RedisOperations
    package: github.com/go-redis/redis/v8
    functions: [Get, Set, Del, Exists, Incr, Decr, HGet, HSet]
    severity: error
    message: "Redis operations should be performed in activities to ensure workflow determinism."

# Known safe external packages that can be used in workflows
safe_external_packages:
  - github.com/pkg/errors      # Error handling - pure functions
  - go.uber.org/zap           # Logging - safe when configured properly  
  - github.com/stretchr/testify # Testing - only used in tests
  - golang.org/x/crypto/bcrypt  # Deterministic crypto operations
